version: '3.8'

services:
  nats:
    image: nats
    ports:
      - "4222:4222"

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comicsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - comics_net

  comics-service:
    build: 
      context: ./comics
      args:
        - MY_ENV_VAR
    ports:
      - "8080:8080"
    depends_on:
      - nats
      - postgres
    env_file:
      - ./comics/.env
    networks:
      - comics_net

  # producer-service:
  #   build: ./producer
  #   ports:
  #     - "50054:50054"
  #   depends_on:
  #     - nats
  #   networks:
  #     - comics_net

  # consumer-service:
  #   build: ./consumer
  #   depends_on:
  #     - nats
  #   networks:
  #     - comics_net

volumes:
  postgres_data:

networks:
  comics_net:
    driver: bridge
